IF OBJECT_ID('SP_ALT_ARTIGO') IS NOT NULL
	DROP PROCEDURE SP_ALT_ARTIGO
GO

CREATE PROCEDURE SP_ALT_ARTIGO
	@ARTCODIGO INT,
	@ARTTITULO VARCHAR(100),
	@ARTAUTOR INT,
	@ARTASSUNTO INT,
	@ARTCONTEUDO TEXT
AS

UPDATE ARTIGOS
SET
	ARTTITULO = @ARTTITULO,
	ARTAUTOR = @ARTAUTOR,
	ARTASSUNTO = @ARTASSUNTO,
	ARTCONTEUDO = @ARTCONTEUDO
WHERE ARTCODIGO = @ARTCODIGO