IF OBJECT_ID('SP_CON_ARTIGO') IS NOT NULL
	DROP PROCEDURE SP_CON_ARTIGO
GO

CREATE PROCEDURE SP_CON_ARTIGO
	@INDEX INT,
	@QTDMAXIMA INT
AS

SELECT ARTCODIGO, ARTTITULO, ARTAUTOR, ARTASSUNTO, ARTCONTEUDO, ARTDATACRIACAO
FROM(
		SELECT 
			ROW_NUMBER() OVER(ORDER BY ARTDATACRIACAO DESC) AS LINHA, ARTCODIGO,
			ARTTITULO, ARTAUTOR, ARTASSUNTO, ARTCONTEUDO, ARTDATACRIACAO
		FROM ARTIGOS
	)AS B
WHERE LINHA BETWEEN @INDEX AND @INDEX + @QTDMAXIMA - 1
