IF OBJECT_ID('SP_ALT_AUTOR') IS NOT NULL
	DROP PROCEDURE SP_ALT_AUTOR
GO

CREATE PROCEDURE SP_ALT_AUTOR
	@AUTCODIGO INT,
	@AUTASSUNTO INT,
	@AUTPROFISSAO VARCHAR(50),
	@AUTNOME VARCHAR(100)
AS

UPDATE AUTORES
SET 
	@AUTASSUNTO = @AUTASSUNTO,
	@AUTPROFISSAO = @AUTPROFISSAO,
	@AUTNOME = @AUTNOME
WHERE AUTCODIGO = @AUTCODIGO 