IF OBJECT_ID('SP_CON_AUTOR') IS NOT NULL
	DROP PROCEDURE SP_CON_AUTOR
GO

CREATE PROCEDURE SP_CON_AUTOR
	@AUTCODIGO INT = 0
AS

IF @AUTCODIGO = 0
BEGIN
	SELECT AUTCODIGO, AUTASSUNTO, AUTPROFISSAO, AUTNOME, AUTDATACRIACAO
	FROM AUTORES
END
ELSE
BEGIN
	SELECT AUTCODIGO, AUTASSUNTO, AUTPROFISSAO, AUTNOME, AUTDATACRIACAO
	FROM AUTORES
	WHERE AUTCODIGO = @AUTCODIGO
END
