IF OBJECT_ID('SP_INC_AUTOR') IS NOT NULL
	DROP PROCEDURE SP_INC_AUTOR
GO

CREATE PROCEDURE SP_INC_AUTOR
	@AUTASSUNTO INT,
	@AUTPROFISSAO VARCHAR(50),
	@AUTNOME VARCHAR(100)
AS

INSERT INTO AUTORES(AUTASSUNTO, AUTPROFISSAO, AUTNOME, AUTDATACRIACAO)
VALUES(@AUTASSUNTO, @AUTPROFISSAO, @AUTNOME, GETDATE())

SELECT @@IDENTITY AS AUTCODIGO