CREATE TABLE ARTIGOS(
	ARTCODIGO INT IDENTITY,
	ARTTITULO VARCHAR(100) NOT NULL,
	ARTAUTOR INT NOT NULL,
	ARTASSUNTO INT NOT NULL,
	ARTCONTEUDO TEXT,
	ARTDATACRIACAO DATETIME,
	CONSTRAINT PK_ARTIGO PRIMARY KEY(ARTCODIGO),
	CONSTRAINT FK_ARTIGO_ARTAUTOR FOREIGN KEY(ARTAUTOR) REFERENCES AUTORES(AUTCODIGO),
	CONSTRAINT FK_ARTIGO_ARTASSUNTO FOREIGN KEY(ARTASSUNTO) REFERENCES ASSUNTOS(ASSCODIGO)
)