IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE XTYPE = 'U' AND NAME = 'AUTORES')
BEGIN
	CREATE TABLE AUTORES(
		AUTCODIGO INT IDENTITY,
		AUTASSUNTO INT NOT NULL,
		AUTPROFISSAO VARCHAR(50),
		CONSTRAINT PK_AUTOR PRIMARY KEY(AUTCODIGO),
		CONSTRAINT FK_AUTOR_AUTASSUNTO FOREIGN KEY(AUTASSUNTO) REFERENCES ASSUNTOS(ASSCODIGO)
	)
END

/*
*	INCLUINDO NOME DO AUTOR
*	INCLUINDO A DATA DE CRIACAO DO AUTOR
*/
IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS T INNER JOIN SYSCOLUMNS C ON T.ID = C.ID WHERE C.NAME = 'AUTNOME')
BEGIN
	ALTER TABLE AUTORES
	ADD AUTNOME VARCHAR(100)
END

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS T INNER JOIN SYSCOLUMNS C ON T.ID = C.ID WHERE C.NAME = 'AUTDATACRIACAO')
BEGIN
	ALTER TABLE AUTORES
	ADD AUTDATACRIACAO DATETIME
END