CREATE TABLE COMENTARIOS(
	COMCODIGO INT IDENTITY,
	COMARTIGO INT NOT NULL,
	COMNOME VARCHAR(40),
	COMEMAIL VARCHAR(120),
	COMCOMENTARIO VARCHAR(1000),
	COMDATA DATETIME NOT NULL,
	CONSTRAINT PK_COMENTARIO PRIMARY KEY(COMCODIGO),
	CONSTRAINT FK_COMENTARIO_COMARTIGO FOREIGN KEY(COMARTIGO) REFERENCES ARTIGOS(ARTCODIGO)
)