IF OBJECT_ID('SP_ALT_ASSUNTO') IS NOT NULL
	DROP PROCEDURE SP_ALT_ASSUNTO
GO

CREATE PROCEDURE SP_ALT_ASSUNTO
	@ASSCODIGO INT,
	@ASSNOME VARCHAR(30)
AS

UPDATE ASSUNTOS
SET ASSNOME = @ASSNOME
WHERE ASSCODIGO = @ASSCODIGO