IF OBJECT_ID('SP_CON_ASSUNTO') IS NOT NULL
	DROP PROCEDURE SP_CON_ASSUNTO
GO

CREATE PROCEDURE SP_CON_ASSUNTO
	@ASSCODIGO INT = 0
AS

IF @ASSCODIGO = 0
BEGIN
	SELECT ASSCODIGO, ASSNOME
	FROM ASSUNTOS
END
ELSE
BEGIN
	SELECT ASSCODIGO, ASSNOME
	FROM ASSUNTOS
	WHERE ASSCODIGO = @ASSCODIGO
END
