IF OBJECT_ID('SP_INC_ASSUNTO') IS NOT NULL
	DROP PROCEDURE SP_INC_ASSUNTO
GO

CREATE PROCEDURE SP_INC_ASSUNTO
	@ASSNOME VARCHAR(30)
AS

INSERT INTO ASSUNTOS(ASSNOME)
VALUES(@ASSNOME)

SELECT @@IDENTITY AS ASSCODIGO